app:
  host: 127.0.0.1
  port: 8000
  keep_alive: 60

models:
  unet_fp16:
    input_size: 384
    batch_size: 20
    tile_res: 512
    to_resize: 384
    overlap: 0.2
    norm_mean: [0.4014, 0.4235, 0.3888]
    norm_std: [0.1708, 0.1555, 0.1457]

inference:
  execution_providers: ['CUDAExecutionProvider','CPUExecutionProvider']
  enable_fallback: True